name: Portfolio | Harvey Fretwell
markdown: kramdown

url: https://harveyf2801.github.io/portfolio
baseurl: /portfolio
permalink: date

sass:
  sass_dir: _sass
  style: compact # possible values: nested expanded compact compressed
